version: 2
updates:
  - package-ecosystem: "npm" # Use npm for the package ecosystem
    directory: "/" # Location of package manifests (package.json, package-lock.json)
    schedule:
      interval: "daily"
    ignore:
      - dependency-type: "development" # Ignore dev dependencies
    allow:
      - dependency-type: "production" # Only allow to update production deps
